apiVersion: apps/v1
kind: Deployment
metadata:
  name: vso-pki-demo
  namespace: default
  labels:
    test: vso-pki-demo
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      test: vso-pki-demo
  template:
    metadata:
      labels:
        test: vso-pki-demo
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: "vso-pki-demo"
      containers:
        - name: example
          image: nginx:latest
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "vso-pki-demo"
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "vso-pki-demo"
                  key: username
          volumeMounts:
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "50Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: X-Custom-Header
                  value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3