apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-kv
spec:
  provider: vault
  secretObjects:
  - data:
    - key: password
      objectName: my-password
    secretName: dbpass
    type: Opaque
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "example-role"
    objects: |
      - objectName: "my-password"
        secretPath: "kvv2/data/secret"
        secretKey: "password"